name: mkdocs
on:
  push:
    branches: ["main", "ci"]
    paths:
      - 'docs/**'
      - '.github/workflows/mkdocs.yml'
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config --global user.name "Nekowiec"
          git config --global user.email "programisci@silveroreteam.pl"
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: ~/.cache 
          restore-keys: |
            mkdocs-material-
      - run: pip install -r requirements.txt
        working-directory: docs
      - run: mkdocs gh-deploy --force
        working-directory: docs